// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHtbhzOq016rMdaBWUewfbpyo-ujsnpnk',
    appId: '1:753080154054:web:f9b47789db73b0803464c7',
    messagingSenderId: '753080154054',
    projectId: 'snap-pazzel',
    authDomain: 'snap-pazzel.firebaseapp.com',
    storageBucket: 'snap-pazzel.firebasestorage.app',
    measurementId: 'G-SD38PECXG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysSNUFxJf65vyiZYxoJtXJeBv_Ig1CEE',
    appId: '1:753080154054:android:762c09b25259371f3464c7',
    messagingSenderId: '753080154054',
    projectId: 'snap-pazzel',
    storageBucket: 'snap-pazzel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACUEPZKpsHUBtNKRLLUMs0BduGkl7tT70',
    appId: '1:753080154054:ios:cb1916eff58811db3464c7',
    messagingSenderId: '753080154054',
    projectId: 'snap-pazzel',
    storageBucket: 'snap-pazzel.firebasestorage.app',
    iosBundleId: 'com.snappuzzle.snapPuzzle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHtbhzOq016rMdaBWUewfbpyo-ujsnpnk',
    appId: '1:753080154054:web:6a962ab40528cf543464c7',
    messagingSenderId: '753080154054',
    projectId: 'snap-pazzel',
    authDomain: 'snap-pazzel.firebaseapp.com',
    storageBucket: 'snap-pazzel.firebasestorage.app',
    measurementId: 'G-HMXK34L5J8',
  );
}
